welcome_page/web/urls.py
from django.contrib import admin
from django.urls import path
from web.views import\
    main, registration, auth,\
    profile, history_page, kuda_page,activity,add_review, reviews
from .views import search

urlpatterns = [
                path('', main, name='main'),
                path('search/', search, name='search'),
                path('registration/', registration, name='registration'),
                path('auth/', auth, name='auth'),
                path('profile/', profile, name='profile'),
                path('history/', history_page, name='history_page'),
                path('kuda_skhodit/', kuda_page, name='kuda_page'),
                path('activity/', activity, name='activity'),
                path('review/add/', add_review, name='review_add'),
                path('reviews/', reviews, name='reviews'),

]

welcome_page/welcome_page/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('web.urls')),
    path('admin/', admin.site.urls),
]

welcome_page/web/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class UserProfile(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=255)

    def __str__(self):
        return self.username


class Place(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    category = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name


class Review(models.Model):
    text = models.TextField(max_length=1500)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)


class Photo(models.Model):
    image = models.ImageField(upload_to='images/')
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

welcome_page/web/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm

from web.models import Review, Photo

User = get_user_model()


class SearchForm(forms.Form):
    search_query = forms.CharField(label='', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Поиск'}))


class RegistrationForm(forms.ModelForm):
    email = forms.EmailField(label='Почта')
    username = forms.CharField(label='Имя пользователя')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Подтверждение пароля')

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['password'] != cleaned_data['password2']:
            self.add_error('password', 'Пароли не совпадают')
        return cleaned_data

    class Meta:
        model = User
        fields = ('email', 'username', 'password', 'password2')


class AuthForm(forms.Form):
    username = forms.CharField(label='Имя пользователя')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль')

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data


class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username']


class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = get_user_model()


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'user', 'place']


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'place', 'review']

welcome_page/web/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login, update_session_auth_hash

from .forms import SearchForm, RegistrationForm, AuthForm, CustomUserChangeForm, ReviewForm, PhotoForm
from .models import Review

User = get_user_model()


def main(request):
    return render(request, 'web/main_page.html', {'main': main})


def search(request):
    if 'q' in request.GET:
        query = request.GET['q']
    else:
        query = ''
    form = SearchForm(initial={'search_query': query})
    context = {'form': form, 'query': query}
    return render(request, 'search_results.html', context)


def registration(request):
    form = RegistrationForm()
    is_success = False
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            user = User(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email']
            )
            user.set_password(form.cleaned_data['password'])
            user.save()
            is_success = True
    return render(request, 'web/registration.html', {'form': form, 'is_success': is_success})


def auth(request):
    form = AuthForm()
    if request.method == 'POST':
        form = AuthForm(data=request.POST)
        if form.is_valid():
            user = authenticate(**form.cleaned_data)
            if user is None:
                form.add_error(None, 'Данные введены неверно')
            else:
                login(request, user)
                return redirect('main')
    return render(request, 'web/auth.html', {'form': form})


@login_required
def profile(request):
    user = request.user
    user_form = CustomUserChangeForm(instance=user)
    password_change_form = PasswordChangeForm(user)

    if request.method == 'POST':
        if 'user_form_submit' in request.POST:
            user_form = CustomUserChangeForm(request.POST, instance=user)
            if user_form.is_valid():
                user_form.save()
                messages.success(request, 'Изменения сохранены.')

        if 'password_change_submit' in request.POST:
            password_change_form = PasswordChangeForm(user, request.POST)
            if password_change_form.is_valid():
                password_change_form.save()
                messages.success(request, 'Пароль изменен успешно.')

    user_reviews = user.review_set.all()

    context = {'user_form': user_form, 'password_change_form': password_change_form, 'user_reviews': user_reviews}
    return render(request, 'web/profile.html', context)


def history_page(request):
    return render(request, 'web/history.html', {'history_page': history_page})


def kuda_page(request):
    return render(request, 'web/kuda.html', {'kuda_page': kuda_page})


def activity(request):
    return render(request, 'web/activity.html', {'activity': activity})


def add_review(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        photo_form = PhotoForm(request.POST, request.FILES)

        if review_form.is_valid() and photo_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()

            photo = photo_form.save(commit=False)
            photo.review = review
            photo.save()

            return redirect('reviews')
    else:
        review_form = ReviewForm()
        photo_form = PhotoForm()

    return render(request, 'add_review.html', {'review_form': review_form, 'photo_form': photo_form})


def reviews(request):
    reviews = Review.objects.all()
    return render(request, 'reviews.html', {'reviews': reviews})

welcome_page/web/templates/web/activity.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Активный отдых</title>
    <style>
        body {
            font-family: 'Courier New', monospace;
            margin: 0;
            padding: 0;
            background-color: #f8f8f7;
            color: #000;
        }

        .container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            flex-direction: column;
        }

        p {
            font-size: 1.2em;
            line-height: 1.6;
            text-align: justify;
        }
        img {
            margin-top: 10px;
            margin-bottom:10px;
            width: 100%;
            height: auto;
            max-width: 100%;
            border-radius: 5px;
        }
        .feature-btn {
            width: 150px;
            height: 50px;
            margin: 10px;
            border-radius: 10px;
            background: #F8F8F7;
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            display: flex;
            align-items: center;
            justify-content: center;
            text-align: center;
            color: #000;
            font-size: 14px;
            font-weight: 400;
            font-family: 'Courier New', sans-serif;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Kazan_Kayak</h1>
        <div class="text-container">
            <div class="image-container">
                <img src='/web/static/activity_kayak.jpeg' alt="Фото Казани">
            </div>
             - это новое место для любителей активного отдыха в центре Казани. Надоели сапы, катамараны? Наше решение - каяки. Это устойчивые плав.средства на которых вы можете бороздить просторы Волги или отправиться в сторону Казанки, чтобы увидеть центр с самого необычного ракурса.



            Можно взять в прокат каяки самостоятельно, а можно отправиться с группой и гидом утром или вечером, на ближайшие острова и получить еще больше впечатлений.



            Для посетителей есть парковка и зона для переодевания.



            Прогулки:
            - По будням 7:00-8:30 "Магия утра", 900₽/чел
            - По будням 18:00-20:00 "Закатные острова", 1100₽/чел
            - В выходные 10:30-12:00 "Ближние острова", 1300₽/чел
            - В выходные 13:30-15:30 "Остров Малибу + самые большие качели Казани", 1400₽/чел
            - В выходные 17:00-20:00 "Монтекристо" (старинное здание водозабора) 1600₽/чел



            Прокат каяков:
            - Ежедневно с 9:00-21:00, 600₽/чел за час.

            - Акция: Счастливая среда. В среду скидка на прогулки 20%.
            - Акция: По будням с 12:00-15:00 на прокат каяков скидка 50% на второй час.



            По всем вопросам: +7 937-778-02-12
            <a class="feature-btn" href="{% url 'reviews'%}">Отзывы</a>
            <a class="feature-btn" href="{% url 'review_add'%}">Добавить отзыв</a>
            <h1>Sup Surf Kazan</h1>
            <div class="image-container">
                <img src='/web/static/surf.jpeg' alt="Фото Казани">
            </div>
            Прокат сап Бордов на АкБарс Арене
            Прокат находится на пирсе АкБарс Арены по адресу: Ямашева 115а/1 на берегу реки Казанки. Отличная идея для свидания или прогулки с друзьями. Вы можете взять сап Борд в надутом состоянии и поплавать удобное для вас время, доплыть до моста Миллениум и обратно — собраться с друзьями и устроить SUP-прогулку живописным заводям реки.

            Подробности и запись на прокат: <h4>https://supsurfkazan.ru/p/prokat-sup/</h4>

            Прогулки по воде и сплавы на сап Бордах
            Прогулка или сплав на сап Бордах большой и дружной компанией в сопровождении инструктора – это отличная идея для любого события, праздника, корпоратива, дня рождения или свидания! Наши маршруты и локации:
            - Голубое озеро
            - Лебяжье озеро
            - Сплав по реке Илеть (протяженность 10 км)
            - Городской маршрут (от АкБарс Арены)
            <a class="feature-btn" href="{% url 'reviews'%}">Отзывы</a>
            <a class="feature-btn" href="{% url 'review_add'%}">Добавить отзыв</a>

        </div>
    </div>
</body>
</html>

welcome_page/web/templates/web/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <style>
        body {
            font-family: 'Courier New', monospace;
            margin: 0;
            padding: 0;
            background-color: #F8F8F7;
        }

        .container {
            margin: 0 auto;
            max-width: 400px;
            padding: 20px;
            margin-top: 100px;
            background-color: #FFF;
            border-radius: 10px;
        }

        h1 {
            text-align: center;
            color: #000;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            margin-bottom: 10px;
            color: #000;
        }

        input {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }

        button {
            padding: 10px;
            background-color: #F8F8F7;
            color: #000;
            border: 1px solid #ccc;
            border-radius: 5px;
            cursor: pointer;
        }


    </style>
</head>
<body>
    <div class="container">
        <h1>Авторизация</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.errors }}
            <label for='id_username'>Имя пользователя:</label>
            <input type="text" name="username" required id="id_username">

            <label for='id_password'>Пароль:</label>
            <input type="password" name="password" required id="id_password">

            <button type="submit">Войти</button>
        </form>
    </div>
</body>
</html>

welcome_page/web/templates/web/kuda.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Куда сходить?</title>
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        .container {
            margin: 0 auto;
            background: #FFF;
            display: flex;
            flex-direction: column;
            font-family: 'Courier New', sans-serif;
        }

        .category-line {
            width: 100%;
            text-align: center;
            margin-top: 20px;
            border-bottom: 2px solid #000;
            margin-bottom: 20px;
        }

        .category-title {
            font-size: 56px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .category-blocks {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
        }

        .category-block {
            width: 30%;
            max-width: calc(30% - 20px);
            height: 150px;
            margin: 20px;
            border-radius: 10px;
            background: #F8F8F7;
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            display: flex;
            align-items: center;
            justify-content: center;
            text-align: center;
            color: #000;
            font-size: 1.25em;
            font-weight: 400;
            font-family: 'Courier New', sans-serif;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="category-line">
            <div class="category-title">Категории</div>
        </div>
        <div class="category-blocks">
            <a class="category-block" href="{%url 'activity'%}">Активный отдых</a>
            <a class="category-block" href="#">Театры</a>
            <a class="category-block" href="#">Музеи</a>
            <a class="category-block" href="#">Кинотеатры</a>
            <a class="category-block" href="#">Спортивные комплексы</a>
            <a class="category-block" href="#">Матчи</a>
            <a class="category-block" href="#">Рестораны и кафе</a>
            <a class="category-block" href="#">Медицинская помощь</a>
            <a class="category-block" href="#">Транспорт</a>
        </div>
    </div>
</body>
</html>

welcome_page/web/templates/web/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Казань</title>
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        .container {
            margin: 0 auto;
            background: #FFF;
            display: flex;
            flex-direction: column;

        }

        .top-panel {
            width: 100%;
            height: 90px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: #F8F8F7;
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            padding: 0 20px;
            box-sizing: border-box;
            font-family: 'Courier New', sans-serif;

        }

        .search-bar {
            width: 650px;
            height: 40px;
            display: flex;

        }

        .search-input {
            width: 80%;
            border: none;
            border-radius: 10px 0 0 10px;
            padding: 5px;
            font-family: 'Courier New', sans-serif;

        }

        .search-btn {
            width: 20%;
            border: none;
            border-radius: 0 10px 10px 0;
            background: #e5e4e4;
            cursor: pointer;
            font-family: 'Courier New', sans-serif;

        }

        .login-btn {
            width: 100px;
            height: 40px;
            border-radius: 10px;
            background: #F8F8F7;
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            font-size: 14px;
            text-align: center;
            line-height: 30px;
            color: #000;
            margin-left: 30px;
            font-family: 'Courier New', sans-serif;

        }

        .register-btn,.auth-btn{
            width: 150px;
            height: 40px;
            border-radius: 10px;
            background: #F8F8F7;
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            font-size: 14px;
            text-align: center;
            line-height: 30px;
            color: #000;
            margin-left: 30px;
            font-family: 'Courier New', sans-serif;

        }


        .button-container {
            display: flex;
            align-items: center;
        }


        .photo-panel {
            position: relative;
            width: 100%;
            height: 296px;
        }

        .background-blur {
            position: relative;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: url(/web/static/Kazan.jpg) lightgray 50% / cover no-repeat;
            filter: blur(2px);
        }

        .welcome-text {
            position: absolute;
            left: 20px;
            top: 50%;
            transform: translateY(-50%);
            z-index: 1;
            color: #000;
            text-align: left;
        }

        .welcome-title {
            font-size: 2.5em;
            font-weight: 500;
            font-family: 'Courier New', sans-serif;

        }

        .city-title {
            color: #FAFAF5;
            font-size: 6em;
            font-weight: 800;
            font-family: 'Arial', sans-serif;

}


        .description {
            height: 200px;
            text-align: center;
            font-size: 20px;
            color: #000;
            margin-left: 100px;
            margin-right: 100px;
            margin-top: 60px;
            font-family: 'Courier New', sans-serif;

        }

        .feature-block {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            margin-top: 20px;
        }

        .feature-btn,
        .feature-btn:visited,
        .feature-btn:hover,
        .feature-btn:active {
            text-decoration: none;
            color: #000;
        }

        .feature-btn {
            width: 33.33%;
            max-width: calc(33.33% - 20px);
            height: 77px;
            margin: 10px;
            border-radius: 10px;
            background: #F8F8F7;
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            display: flex;
            align-items: center;
            justify-content: center;
            text-align: center;
            color: #000;
            font-size: 1.25em;
            font-weight: 400;
            font-family: 'Courier New', sans-serif;

        }

        .feature-title {
            font-size: 30px;
            margin-left: 30px;
            font-family: 'Courier New', sans-serif;

        }

        @media only screen and (max-width: 768px) {
            .top-panel {
                flex-direction: column;
                height: auto;
            }

            .search-bar, .login-btn, .register-btn {
                width: 100%;
                margin: 10px 0;
            }

            .photo-panel {
                height: 300px;
            }

            .welcome-text {
                left: 10px;
                width: calc(100% - 20px);
            }

            .welcome-title {
                font-size: 3em;
            }

            .city-title {
                font-size: 3em;
            }

            .description {
                font-size: 12px;
            }

            .feature-btn {
                flex: 0 0 100%;
                max-width: none;
            }
        }
        .profile-button {
            display: flex;
            align-items: center;
            padding: 10px;
            border: 2px solid #000;
            border-radius: 100%;
            cursor: pointer;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="top-panel">
            <form method="get" action="search" class="search-bar">
                <input type="text" name="q" placeholder="Введите желаемый запрос" class="search-input">
                <button type="submit" class="search-btn">Поиск</button>
            </form>
            {% if not user.is_anonymos %}
                <div class="profile-button" onclick="location.href='profile'">
                    <span>{{ user.username }}</span>
                </div>
            {% else %}
                <div class="button-container">
                    <a href="auth.html">
                        <button class="auth-btn">Войти</button>
                    </a>
                    <a href="registration.html">
                        <button class="register-btn">Регистрация</button>
                    </a>
                </div>
            {% endif %}
        </div>

        <div class="photo-panel">
            <div class="background-blur"></div>
            <div class="welcome-text">
                <div class="welcome-title">WELCOME TO</div>
                <div class="city-title">KAZAN</div>
            </div>
        </div>

        <div class="description">
            Казань — город, в котором сливаются древность и современность, история и инновации. Столица Республики Татарстан, расположенная на берегах Волги, привлекает своим разнообразием, культурным наследием и уникальным колоритом. В этом увлекательном путеводителе по Казани мы погрузимся в ее богатую историю, исследуем культурные богатства, оценим местное гастрономическое мастерство и рассмотрим возможности для активного отдыха.        </div>
        <div class="feature-title">Познакомьтесь с городом получше</div>
        <div class="feature-block">
            <a class="feature-btn" href="{% url 'history_page' %}">История Казани</a>
            <a class="feature-btn" href="{% url 'kuda_page' %}">Куда сходить?</a>
            <button class="feature-btn">Наша гордость</button>
        </div>
    </div>
</body>
</html>

welcome_page/web/templates/web/profile.html
<!-- profile.html -->
<!-- profile.html -->
<!DOCTYPE html>
{% block content %}
    <div class="container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <h1>Здравствуйте, {{ user.username }}!</h1>

        <h2>Настройки профиля</h2>
        <form method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            <button type="submit" name="user_form_submit">Сохранить изменения</button>
        </form>

        <h2>Смена пароля</h2>
        <form method="post">
            {% csrf_token %}
            {{ password_change_form.as_p }}
            <button type="submit" name="password_change_submit">Сменить пароль</button>
        </form>

        <h2>Отзывы пользователя</h2>
        {% if user_reviews %}
            <ul>
                {% for review in user_reviews %}
                    <li>{{ review.text }} - {{ review.created_at }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Пользователь еще не оставил отзывов.</p>
        {% endif %}
    </div>
{% endblock %}

welcome_page/web/templates/web/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <style>
        body {
            font-family: 'Courier New', monospace;
            margin: 0;
            padding: 0;
            background-color: #F8F8F7;
        }

        .container {
            margin: 0 auto;
            max-width: 400px;
            padding: 20px;
            margin-top: 100px;
            background-color: #FFF;
            border-radius: 10px;
        }

        h1 {
            text-align: center;
            color: #000;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            margin-bottom: 10px;
            color: #000;
        }

        input {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }

        button {
            padding: 10px;
            background-color: #F8F8F7;
            color: #000;
            border: 1px solid #ccc;
            border-radius: 5px;
            cursor: pointer;
        }


    </style>
</head>
<body>
    <div class="container">
        <h1>Регистрация</h1>
        {% if is_success %}
            <p><b>Вы зарегистрированы!</b></p>
        {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.errors }}

            <label for='id_email'>Почта:</label>
            <input type="email" name="email" required id="id_email">

            <label for='id_username'>Имя пользователя:</label>
            <input type="text" name="username" required id="id_username">

            <label for='id_password'>Пароль:</label>
            <input type="password" name="password" required id="id_password">

            <label for='id_password'>Подтвердите пароль:</label>
            <input type="password" name="password2" required id="id_password2">

            <button type="submit">Регистрация</button>
        </form>
        {% endif %}
    </div>
</body>
</html>

welcome_page/web/templates/web/review_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Review</title>
</head>
<body>
    <h1>Add Review</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ review_form.as_p }}
        {{ photo_form.as_p }}

        <button type="submit">Submit Review</button>
    </form>

    {% if review_form.errors or photo_form.errors %}
        <p>There was an error in the submitted form. Please correct the errors.</p>
    {% endif %}

    {% if review_form.instance.text %}
        <h2>Your Review:</h2>
        <p>{{ review_form.instance.text }}</p>
        {% if review_form.instance.created_at %}
            <p>Created at: {{ review_form.instance.created_at }}</p>
        {% endif %}
    {% endif %}

    {% if photo_form.instance.image %}
        <h2>Your Photo:</h2>
        <img src="{{ photo_form.instance.image.url }}" alt="Review Photo">
    {% endif %}
</body>
</html>

welcome_page/web/templates/web/reviews.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reviews</title>
</head>
<body>
    <h1>All Reviews</h1>

    {% for review in reviews %}
        <div>
            <p>{{ review.text }}</p>
            <p>{{ photo.image }}</p>
            <p>Created at: {{ review.created_at }}</p>
        </div>
        <hr>
    {% endfor %}

    {% if not reviews %}
        <p>Отзывов пока нет!</p>
    {% endif %}
</body>
</html>